### ISSUE TITLE
Spectrometer/Spectrogram Plugin

### ISSUE THREAD

**Issue by BillyDM** [MeadowlarkDAW/project-board#37]
- Should be able to switch between the "classic" style (like Voxengo Span) and the "FL-style" (like the spectrogram in Fruity Wavecandy).
- [`Wolf Spectrum`] is a good one to reference for the "FL-style" one.

[`Wolf Spectrum`]: https://github.com/wolf-plugins/wolf-spectrum

**Comment by mwallenfang** [comment]
Can I be assigned to this one?

**Comment by trynsta** [comment]
I would be nice to have "Reassignment method" (https://en.wikipedia.org/wiki/Reassignment_method) implemented in spectrogram. This video explain this topic: https://www.youtube.com/watch?v=8J4LE9UpxYU.
