### ISSUE TITLE
Add tooltips to browser items

### ISSUE THREAD

**Issue by geom3trik** [MeadowlarkDAW/project-board#64]
Add tooltips to browser items to show full filenames without needing to expand the browser panel.

**Comment by dustyfingers** [comment]
I have started working on this, and I have the hover in/out events set up and firing at the correct times locally. I am working on building the actual tooltip now. should this be on hover AND when flipping through the items with arrows on the keyboard for all of the items in the toolbar? also, should the tooltips only appear when the title of the item overflows the width of its container?

I am coming from react, with a bit of **super** light rust experience, so don't expect ludicrous speed from me yet! haha. but I'd love to help out where I can.

**Comment by geom3trik** [comment]
Ooh good questions. I was going to consult Ableton Live for reference but realised that it doesn't have any tooltips at all for the browser. Probably someone with more DAW experience than myself can chime in here but I would say that the tooltips should not appear when using the arrow keys and only when hovering with the mouse, mainly because we can probably show the full name, or more of it, at the bottom where the preview+controls will be. 

I think also that the tooltip should only appear when the label is too short to show the full text. Now we probably need to add something to vizia for that so we can determine when the text is being clipped. I think for now it's fine to show the tooltip every time and we can fix it later.

**Comment by dustyfingers** [comment]
copy that, yeah I know how to do that super easily in React, but Vizia is an entirely different (super cool) world so I was kind of at a loss as to how to get that information from the browser item. okay I can add them for all hover events for now. thanks!

**Comment by dustyfingers** [comment]
copy that, yeah I know how to do that super easily in React, but Vizia is an entirely different (super cool) world so I was kind of at a loss as to how to get that information from the browser item. okay I can add them for all hover events for now. thanks!
